

drop database if exists sistema;

create database sistema;-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 07:18:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`persona` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `edad` INT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `llave usuario`
  FOREIGN KEY (`id_usuario`)
  REFERENCES `sistema`.`persona` (`id_usuario`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`tipo_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`tipo_rol` (
  `id_tipo_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`roles` (
  `id_usuario` INT NULL,
  `id_tipo_rol` INT NULL,
  CONSTRAINT `fk_usuario_has_roles_usuario1`
  FOREIGN KEY (`id_usuario`)
  REFERENCES `sistema`.`usuario` (`id_usuario`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_roles_roles1`
  FOREIGN KEY (`id_tipo_rol`)
  REFERENCES `sistema`.`tipo_rol` (`id_tipo_rol`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`tipo_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`tipo_permiso` (
  `id_tipo_permiso` INT NOT NULL,
  `nombre_tipo_permiso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`roles_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`roles_permisos` (
  `id_tipo_rol` INT NOT NULL,
  `id_tipo_permiso` INT NOT NULL,
  CONSTRAINT `fk_tipo_permiso_has_roles_tipo_permiso1`
  FOREIGN KEY (`id_tipo_rol`)
  REFERENCES `sistema`.`tipo_rol` (`id_tipo_rol`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_permiso_has_roles_roles1`
  FOREIGN KEY (`id_tipo_permiso`)
  REFERENCES `sistema`.`tipo_permiso` (`id_tipo_permiso`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sistema`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`acceso` (
  `id_usuario` INT NULL,
  `id_modulo` INT NULL,
  CONSTRAINT `llave_accesos`
  FOREIGN KEY (`id_usuario`)
  REFERENCES `sistema`.`usuario` (`id_usuario`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sistema`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`modulo` (
  `nombre` VARCHAR(45) NULL,
  `id_modulo` INT NOT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sistema`.`pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`pagina` (
  `id_pagina` INT NOT NULL,
  `id_modulo` INT NULL,
  `id_roles` INT NULL,
  PRIMARY KEY (`id_pagina`),
  CONSTRAINT `llave pagina`
  FOREIGN KEY (`id_modulo`)
  REFERENCES `sistema`.`modulo` (`id_modulo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `llave 2`
  FOREIGN KEY (`id_roles`)
  REFERENCES `sistema`.`roles` (`id_tipo_rol`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;



USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`persona` (
  `id_usuario` INT(10) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `edad` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`usuario` (
  `id_usuario` INT(10) NOT NULL,
  `nombre_usuario` VARCHAR(30) NOT NULL,
  `clave` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `llave_usuario`
  FOREIGN KEY (`id_usuario`)
  REFERENCES `sistema`.`usuario` (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`tipo_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`tipo_rol` (
  `id_tipo_rol` INT(10) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`roles` (
  `id_rol` INT(10) NULL DEFAULT NULL,
  `id_usuario` INT(10) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`tipo_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`tipo_permiso` (
  `id_tipo_permiso` INT(10) NULL DEFAULT NULL,
  `nombre` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`Modulo` (
  `id_modulo` INT(10) NULL DEFAULT NULL,
  `nombre` VARCHAR(10) NULL DEFAULT NULL,
  `id_usuario` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`acceso` (
  `id_usuario` INT(10) NULL DEFAULT NULL,
  `id_modulo` INT(30) NULL DEFAULT NULL,
  CONSTRAINT `llave_acceso`
  FOREIGN KEY (`id_modulo`)
  REFERENCES `sistema`.`modulo` (`id_modulo`),
  CONSTRAINT `llave2_acceso`
  FOREIGN KEY (`id_usuario`)
  REFERENCES `sistema`.`usuario` (`id_usuario`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sistema`.`pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`pagina` (
  `id_permiso` INT(10) NULL DEFAULT NULL,
  `id_modulo` INT(10) NULL DEFAULT NULL)
ENGINE = InnoDB;

ALTER TABLE `acceso` ADD FOREIGN KEY (`id_modulo`) REFERENCES `modulo`(`id_modulo`) ON DELETE RESTRICT ON UPDATE RESTRICT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tipo_permiso VALUES(1,'crear');
insert into tipo_permiso VALUES(2,'leer');
insert into tipo_permiso VALUES(3,'actualizar');
insert into tipo_permiso VALUES(4,'eliminar');


INSERT into tipo_rol values(1, 'CEO');
INSERT into tipo_rol values(2, 'Gerente');
INSERT into tipo_rol values(3, 'supervisor');
INSERT into tipo_rol values(4, 'Agente');

insert into modulo values(1,'ventas');
insert into modulo values(1,'cobtros');
insert into modulo values(1,'finanzas');
insert into modulo values(1,'contabilidad');

insert into sistema.modulo(id_modulo,nombre) values(1,'ventas');
insert into sistema.modulo(id_modulo,nombre) values(1,'cobtros');
insert into sistema.modulo(id_modulo,nombre) values(1,'finanzas');
insert into sistema.modulo(id_modulo,nombre) values(1,'contabilidad');

insert into roles values(1,1);

insert into roles_permisos values(1,1);

